# Generated by Django 3.2.10 on 2021-12-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldevices',
            name='platform',
            field=models.CharField(default='cisco_xr', max_length=20),
        ),
    ]
