# Generated by Django 3.2.10 on 2021-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0002_alldevices_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldevices',
            name='allow_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alldevices',
            name='hostkey_verify',
            field=models.BooleanField(default=False),
        ),
    ]
