# Generated by Django 3.2.10 on 2021-12-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netapp', '0003_auto_20211211_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alldevices',
            old_name='ip',
            new_name='host',
        ),
    ]
